### ISSUE TITLE
点击“配置”按钮会导致程序崩溃

### ISSUE THREAD

**Issue by jixiaobai19** [travellerse/RainClassroomAssistant#4]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在使用vscode运行RainClassroomAssistant.py文件以使用摸鱼课堂的过程中，在任何时刻点击“配置”按钮均会导致程序在卡顿几秒后闪退，怀疑有内存溢出现象。以下为程序崩溃报告，其中"e:\Program Files (x86)\RainClassroomAssistant\RainClassroomAssistant-main3"为code ZIP内的文件解压后的存放路径：

Traceback (most recent call last):
  File "e:\Program Files (x86)\RainClassroomAssistant\RainClassroomAssistant-main3\UI\MainWindow.py", line 297, in show_config
    config_ui.load_config(self.config)
  File "e:\Program Files (x86)\RainClassroomAssistant\RainClassroomAssistant-main3\UI\Config.py", line 337, in load_config
    config["answer_config"]["answer_delay"]["custom"]["percent"]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'percent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Program Files (x86)\RainClassroomAssistant\RainClassroomAssistant-main3\UI\MainWindow.py", line 302, in show_config
    config_ui.load_config(self.config)
  File "e:\Program Files (x86)\RainClassroomAssistant\RainClassroomAssistant-main3\UI\Config.py", line 337, in load_config
    config["answer_config"]["answer_delay"]["custom"]["percent"]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'percent'

### Classification

雨课堂

### Version

3.11.5150

### 截图或录屏

_No response_

### 还有别的吗？

摸鱼课堂每次启动时均会反馈“配置文件读取失败，已重新生成”，可能与本问题存在关联。

**Comment by travellerse** [comment]
由于我这边无法复现，请检查文件
C:\Users\\[username]\AppData\Roaming\RainClassroomAssistant\config.json
是否存在键值answer_config.answer_delay.custom.percent
可能是无法存取此路径文件导致的错误

**Comment by jixiaobai19** [comment]
> 由于我这边无法复现，请检查文件 C:\Users\[username]\AppData\Roaming\RainClassroomAssistant\config.json 是否存在键值answer_config.answer_delay.custom.percent 可能是无法存取此路径文件导致的错误

经检查该问题是由于该路径下v0.0.4老版本生成的配置文件与新版不兼容导致的，现已得到解决，感谢作者
